In [14]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
movies = pd.read_csv(r"C:\Users\Prem Vilas Nikam\DSBDA practical and mini project\Mini_Project\dataset\movie_dataset.csv")

movies.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [17]:
movies.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='str')

In [18]:

features = ['keywords', 'cast', 'genres', 'director']


for feature in features:
    movies[feature] = movies[feature].fillna('')

In [19]:
def combine_features(row):
    return row['keywords'] + " " + row['cast'] + " " + row['genres'] + " " + row['director']

movies['combined'] = movies.apply(combine_features, axis=1)

movies[['title', 'combined']].head()

,title,combined
0,Avatar,culture clash future space war space colony so...
1,Pirates of the Caribbean: At World's End,ocean drug abuse exotic island east india trad...
2,Spectre,spy based on novel secret agent sequel mi6 Dan...
3,The Dark Knight Rises,dc comics crime fighter terrorist secret ident...
4,John Carter,based on novel mars medallion space travel pri...

In [20]:
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(movies['combined'])

In [22]:
similarity = cosine_similarity(tfidf_matrix)

In [27]:
import random   

def recommend(movie_name):
    
    movie_index = movies[movies['title'] == movie_name].index
    
    if len(movie_index) == 0:
        print("Movie not found")
        return
    
    movie_index = movie_index[0]
    
    scores = list(enumerate(similarity[movie_index]))
    
    sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
    
    top_movies = sorted_scores[1:15]
    
    random_movies = random.sample(top_movies, 5)
    
    print(f"Because you watched: {movie_name}\n")
    print("Recommended movies:\n")
    
    for i in random_movies:
        print(movies.iloc[i[0]].title)

In [29]:
recommend("Avatar")

Because you watched: Avatar

Recommended movies:

Star Trek Beyond
Jason X
Alien
Machete Kills
Galaxy Quest